name: CI → Build & Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using the service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup gcloud SDK (this action installs it safely)
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: 'beta'

      # Configure Docker to use Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      # Build and push image to Artifact Registry
      - name: Build and push Docker image
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          REGION: ${{ secrets.GCP_REGION }}
          ARTIFACT_REPOSITORY: ${{ secrets.ARTIFACT_REPOSITORY }}
        run: |
          IMAGE_URI="${REGION}-docker.pkg.dev/${GCP_PROJECT}/${ARTIFACT_REPOSITORY}/${{ github.repository }}:${GITHUB_SHA::7}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        env:
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          REGION: ${{ secrets.GCP_REGION }}
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_URI \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --quiet
