name: CI → Build & Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.GCP_PROJECT }}-docker
  # IMAGE_URI will be constructed during the run

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}

      - name: Install Google Cloud SDK components
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk

      - name: Configure Docker credential helper for Artifact Registry
        run: |
          gcloud auth configure-docker ${ { secrets.GCP_REGION } }-docker.pkg.dev --quiet
        # NOTE: the line above will work after gcloud installed and auth.

      - name: Build Docker image
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          REGION: ${{ secrets.GCP_REGION }}
          ARTIFACT_REPOSITORY: ${{ secrets.ARTIFACT_REPOSITORY }}
        run: |
          IMAGE_URI="${{ secrets.GCP_REGION }}-docker.pkg.dev/${GCP_PROJECT}/${ARTIFACT_REPOSITORY}/${{ github.repository }}:${GITHUB_SHA::7}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        env:
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          REGION: ${{ secrets.GCP_REGION }}
        run: |
          # Deploy the just-pushed image
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_URI \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --quiet
